language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./$SCRIPT
env:
  global:
  - secure: iS8MtXltyXj/T1EgpZaMillH/SuMAinX7ma5ER1Zt54F9CS3/tH+pG9Yx8uM8sUOZU90xvmN0AZ4HI4sPzquj8UUS+a0Xoj4kj43eGG90bi3nqtdNtopQOZpLFhvm7+tMzRztHLocvlPWLu1l8xHeGycm+J7X1sx+CW+p4uotPE=
  - PINS="nbd:. nbd-lwt-unix:. nbd-tool:."
  - SCRIPT=.travis-docker.sh
  matrix:
  - PACKAGE=nbd  DISTRO="debian-unstable" OCAML_VERSION=4.03.0
  - PACKAGE=nbd  DISTRO="debian-unstable" OCAML_VERSION=4.04.2
  - PACKAGE=nbd  DISTRO="debian-unstable" OCAML_VERSION=4.05.0
  - PACKAGE=nbd-lwt-unix  DISTRO="debian-unstable" OCAML_VERSION=4.03.0
  - PACKAGE=nbd-lwt-unix  DISTRO="debian-unstable" OCAML_VERSION=4.04.2
  # Upload docs for both nbd and nbd-lwt-unix
  - PACKAGE=nbd-lwt-unix  DISTRO="debian-unstable" OCAML_VERSION=4.05.0 SCRIPT=.travis-docker-docgen.sh
  - PACKAGE=nbd-tool  DISTRO="debian-unstable" OCAML_VERSION=4.03.0
  - PACKAGE=nbd-tool  DISTRO="debian-unstable" OCAML_VERSION=4.04.2
  - PACKAGE=nbd-tool  DISTRO="debian-unstable" OCAML_VERSION=4.05.0
branches:
  only: master
